language: node_js
node_js:
  - "10.14.2"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install

script:
  - echo "Building!!"
  - npm run build

deploy:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

after_success:
  - echo "Succes - Deployed"
